#!/bin/bash

dir=/Users/petermenzies/SeaSketch/azores

inpath=$dir/azo-ous/outputs/flores-corvo-santamaria/shapefiles/corvo
outpath=$dir/heatmaps

docker-compose run --rm --service-ports -v $inpath:/work/input -v $outpath:/work/output  sapmap


