#!/bin/bash

inpath=/Users/petermenzies/SeaSketch/azores/azo-ous/outputs/phase-3/shapefiles/terceira
# inpath=/Users/petermenzies/SeaSketch/azores/azo-ous/outputs/phase-3/shapefiles/saomiguel
# inpath=/Users/petermenzies/SeaSketch/azores/azo-ous/outputs/phase-3/shapefiles/saojorge
outpath=/Users/petermenzies/Library/CloudStorage/Box-Box/GIS/Waitt/Azores/Data_Products/Heatmaps/Phase_3_heatmaps
# outpath=/Users/petermenzies/Downloads

docker-compose run --rm --service-ports -v $inpath:/work/input -v $outpath:/work/output  sapmap


