#!/bin/bash

inpath=/Users/menzies/Projects/maldives/eez-shapes
outpath=/Users/menzies/Projects/maldives/eez-heatmaps

docker-compose run --rm --service-ports -v $inpath:/work/input -v $outpath:/work/output  sapmap


