#!/bin/bash

dir=/Users/petermenzies/SeaSketch/maldives

inpath=$dir/combined_shps
outpath=$dir/heatmaps

docker-compose run --rm --service-ports -v $inpath:/work/input -v $outpath:/work/output  sapmap


