#!/usr/bin/env python3

# print shapes in json config format

import glob

shps = glob.glob("input/*shp")

for i in range(0, len(shps)):
    if i < len(shps)-1:
        print(f'{{"infile": "/work/{shps[i]}"}},')
    else:
        print(f'{{"infile": "/work/{shps[i]}"}}')

