name: "Publish Docs"

on:
  push:
    branches:    
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
    - name: Commit documentation changes
      run: |
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    - name: Push changes
      uses: jbrooksuk/github-subtree-push-action@master
      with:
        branch: gh-pages
        directory: docs/_build/html
        github_token: ${{ secrets.GITHUB_TOKEN }}
    # ===============================