name: "Publish Docs"

on:
  push:
    branches:    
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
    - name: Commit documentation changes
      run: |
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        remote_repo="https://${GITHUB_ACTOR}:${secrets.GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git subtree push --prefix docs/_build/html "${remote_repo}" origin gh-pages
        # The above command will fail if no changes were present, so we ignore
        # that.    
    # ===============================
