name: "Test Docs"
on: 
- pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        python -m pip install -r requirements_dev.txt
        python -m pip install -e .
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"